### ISSUE TITLE
Link is damaged.

### ISSUE THREAD

**Issue by 2p990i9hpral** [juliojj/app-real-age#1]
I can't download train/test/val dataset and pre-trained model
repair please.

**Comment by juliojj** [comment]
Sorry for the inconvenient. The server where the data was placed is being restored. The data will be available in the next few days.

**Comment by juliojj** [comment]
In the meantime our server is being restored, the preprocessed data and the pretrained model will be temporary available in the following link: https://drive.google.com/file/d/1KF_eq_-1uv1zHCCpiNTM00h3APuShLbf/view?usp=sharing
Please let me know if you have any problem.

**Comment by 2p990i9hpral** [comment]
thank you!

**Comment by wangxinyue11** [comment]
> I can't download train/test/val dataset and pre-trained model
> repair please.
Can I provide a download link for me? The following link is also invalid.

**Comment by wangxinyue11** [comment]
> I can't download train/test/val dataset and pre-trained model
> repair please.

Can you give me a download link? Thank you very much! I really need it now.

**Comment by juliojj** [comment]
https://github.com/juliojj/app-real-age/issues/3#issuecomment-509110299
