### ISSUE TITLE
Inference on single Image

### ISSUE THREAD

**Issue by marcomiglionico94** [juliojj/app-real-age#2]
I would like to use the model to make inference on a single image. The question is how can I obtain the extra features( gender, race, makeup and facial expression ) for a new image that I want to give as input to the network? Do you have the code to extract them?
Thanks

**Comment by juliojj** [comment]
Sorry for the late reply. For some reason, github is not sending me notifications. We did not focus on the automatic recognition of such attributes as our goal was to analyse human bias in age perception and how it could improve real age recognition when tackled jointly (without being influenced by the accuracy of attribute recognition approaches). However, we mention in the paper (more precisely, in section III-A) there are some works you could use for that. I believe gender, ethnicity and facial expression recognition may be easier to address, as these topics are somehow very well studied in the literature.
