### ISSUE TITLE
code issues

### ISSUE THREAD

**Issue by wangxinyue11** [juliojj/app-real-age#5]
Sorry to bother you, I would like to ask a question I encountered in reproducing this paper. This file: vgg16_weights_tf_dim_ordering_tf_kernels.h5
Which directory should I put in, because of the network, the online download has failed, the code prompts that the file could not be found or is outdated. How should I modify it?

**Comment by juliojj** [comment]
these are the pretrained weights loaded by keras when you run the model for the first time (and particularly when doing the training). This step may be avoided if you select to load the pretrained model provided by me (at test stage). If you are not able to download that file when running the code, you can download it from their repository and put it (if I am not wrong) inside ~/.keras/models

**Comment by wangxinyue11** [comment]
Thank you for your mention, the problem is solved.
