### ISSUE TITLE
Test the results

### ISSUE THREAD

**Issue by melih-unsal** [juliojj/app-real-age#6]
How do I test the model on my single photo ? How can I prepare the extra labels?

**Comment by juliojj** [comment]
Please, first check the following issue: https://github.com/juliojj/app-real-age/issues/2#issue-441787842

Then, in case you want to (manually or automatically) detect and inform the extra labels of some new sample/image, they need to be organized as one-hot vector as described next: 

sample_x_extra_labels = [gender, ethnicity, makeup, emotion]

Options are:
--
gender (male) = [1, 0] 
gender (female) = [0, 1]
--
ethnicity (asian) = [1, 0, 0]
ethnicity (african-american) = [0, 1, 0]
ethnicity (caucasian) = [0, 0, 1]
---
makeup (makeup) =  [1, 0, 0, 0]
makeup (no makeup) =  [0, 1, 0, 0]
makeup (not clear) =  [0, 0, 1, 0]
makeup (very subtle) =  [0, 0, 0, 1]
---
emotion (happy) =  [1, 0, 0, 0]
emotion (slightly happy) =  [0, 1, 0, 0]
emotion (neutral) =  [0, 0, 1, 0]
emotion (other) =  [0, 0, 0, 1]

The resulting vector should concatenate all these informations, for instance:
sample_x_extra_labels = [1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]
In this example, "male, asian, makeup, happy"

I hope it helps. 
Best

**Comment by juliojj** [comment]
Please, first check the following issue: https://github.com/juliojj/app-real-age/issues/2#issue-441787842

Then, in case you want to (manually or automatically) detect and inform the extra labels of some new sample/image, they need to be organized as one-hot vector as described next: 

sample_x_extra_labels = [gender, ethnicity, makeup, emotion]

Options are:

gender (male) = [1, 0] 
gender (female) = [0, 1]

ethnicity (asian) = [1, 0, 0]
ethnicity (african-american) = [0, 1, 0]
ethnicity (caucasian) = [0, 0, 1]

makeup (makeup) =  [1, 0, 0, 0]
makeup (no makeup) =  [0, 1, 0, 0]
makeup (not clear) =  [0, 0, 1, 0]
makeup (very subtle) =  [0, 0, 0, 1]

emotion (happy) =  [1, 0, 0, 0]
emotion (slightly happy) =  [0, 1, 0, 0]
emotion (neutral) =  [0, 0, 1, 0]
emotion (other) =  [0, 0, 0, 1]

The resulting vector should concatenate all these information, for instance:
sample_x_extra_labels = [1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0]
In this example, "male, asian, makeup, happy"

I hope it helps. 
Best

**Comment by melih-unsal** [comment]
Thanks , it works however I cannot understand what predict function outputs. It gives 2 numbers none of which are related to ages. What do they mean?

**Comment by juliojj** [comment]
I am sorry, I forgot to mention this in the documentation. To train the model, all age values were normalized using a normalization factor = 100 (assumed to be the maximum age in the adopted database). This way, all train/validation/test labels were in the range of [0, ..., 1]. Input images were also normalized to be in the range of [0,...,1]. The two output values are (normalized) apparent and real age, respectively. To get the resulting ages (apparent and real) you may need to multiply these values by 100.
